#!/bin/sh
if ! zopen list --installed | grep "^man-db\$"; then
  : # No man-db installed
else
  echo "- Updating man-db database after package removal..."
  if ! mandb >/dev/null 2>&1; then
    printWarning "man-db update completed with non-zero return code."
    printWarning "Re-run 'mandb' manually for additional information."
  else 
    echo "- Update of man-db complete."
  fi
fi
