#!/bin/sh
# Generate man1/zopen.1.gz from man1/README.md

set -e

curdir="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
mandir="${curdir}/man1"
docker run -ti -v ${mandir}:/tmp/ dantesignal31/markdown2man:latest /tmp/README.md zopen
rm -rf ${mandir}/tmp*
