#!/bin/sh
this="zopen-config-list"
printVerbose "Running '${this}' script"
cfgFile="${ZOPEN_ROOTFS}/etc/zopen-config"
cfgFileWorking="${ZOPEN_ROOTFS}/tmp/zopen-config.tmp"
envFile="${ZOPEN_ROOTFS}/etc/zopen/zopen.env"
envFileWorking="${envFile}.working"
# Running in a "clean" environment - this requires an executable version of the
# configuration file

cp -f "${cfgFile}" "${cfgFileWorking}"
chmod +x "${cfgFileWorking}"

if ! (env -i "${cfgFileWorking}" --knv | sort > "${envFileWorking}" ); then
  printSoftError "Unable to generate zopen environment key/value pair"
  return 1
fi
if [ ! -e "${envFileWorking}" ]; then
  printSoftError "Could not locate working file"
  return 1
fi
if ! [ -e "${envFile}" ]; then
  mv "${envFileWorking}" "${envFile}"
  return 0
fi
if ! diff=$(diff "${envFileWorking}" "${envFile}"); then
  printSoftError "${diff}"
  printSoftError "Could not compute difference in new key-value pairs. Correct errors and run and redirect '${ZOPEN_ROOTFS}/etc/zopen-config knv | sort' manually."
  return 1
fi
