#!/bin/sh
check_system() {
  PROCESSOR=$(/bin/uname -m)
  RELEASE=$(/bin/uname -r | /bin/sed "s/\.[0-9]*//")
  PLATFORM=$(/bin/uname -s)

  # Checking if the platform is z/OS
  if [ ! ${PLATFORM} = "OS/390" ]; then
    echo "ERROR: This system is not a z/OS system"
    exit 1
  fi

  # Checking if the OS is up to date
  if [ ${RELEASE} -lt 29 ]; then
      echo "ERROR: An OS level (${RELEASE}) lower than z/OS V3R1 (29) has been detected."
      exit 1
  fi
}

check_system
