#!/bin/sh
pkg=$1
metadataFile=$2
[ -z "${pkg}" ] && return
# shellcheck disable=SC2154
if ! "${bypassPrereqs}"; then
  systemPrereqs=$(jq -r '.product.system_prereqs // empty' "${metadataFile}" 2>/dev/null)
  systemPrereqs="${systemPrereqs} zos24" # zos24 should be min requirement - always add it
  if [ -n "${systemPrereqs}" ]; then
    if [ ! -d "${ZOPEN_SYSTEM_PREREQS_DIR}" ]; then
      printWarning "${ZOPEN_SYSTEM_PREREQS_DIR} does not exist. You should upgrade meta. Bypassing prereq check."
    fi
    for prereq in $(echo "${systemPrereqs}" | xargs | tr ' ' '\n' | sort -u); do
      printHeader "Checking system pre-req requirement '${prereq}'"
      if [ -e "${ZOPEN_SYSTEM_PREREQS_DIR}/${prereq}" ]; then
        if ! /bin/sh -c "${ZOPEN_SYSTEM_PREREQS_DIR}/${prereq}"; then
          printError "Failed system pre-req check '${prereq}'. If you wish to bypass this, install with --bypass-prereq-checks"
        fi
      else
        printWarning "${ZOPEN_SYSTEM_PREREQS_DIR}/${prereq} does not exist. You should upgrade meta. Bypassing prereq check."
      fi
    done
  fi
fi
