#!/usr/bin/env python3
"""
Sanitizes raw HTML generated by groff from man pages for use in VitePress.

Groff's mandoc -Thtml output frequently contains:
1. Malformed headers: <h2>HEADING\n<a name="HEADING"></a>\n</h2>
2. Orphaned closing tags (e.g. <p><b>Verbs:</b></p></table>)
3. Unclosed inline tags (e.g. <b>Text</p>)
4. Raw URLs in angle brackets (<https://...>) which VitePress/Vue interprets as component tags

This script normalizes headings, auto-balances all HTML tags, discards orphaned closing tags,
converts URLs into anchor links, and wraps the output in VitePress-compatible container markdown.
"""

import sys
import os
import re
import argparse

VOID_TAGS = {'br', 'hr', 'img', 'input', 'meta', 'link'}
TAG_REGEX = re.compile(r'(<(/)?([a-zA-Z0-9]+)([^>]*)>)')

def sanitize_man_html(raw_content: str) -> str:
    # 1. Extract content between <body> and </body> if present
    body_match = re.search(r'<body>(.*?)</body>', raw_content, re.DOTALL | re.IGNORECASE)
    content = body_match.group(1) if body_match else raw_content

    # 1. Clean existing wrappers if input was an already-wrapped markdown file
    content = re.sub(r'<div\s+v-pre\s+class="man-page-content">', '', content, flags=re.IGNORECASE)
    content = re.sub(r'<div\s+class="header-with-back">.*?</div>\s*</div>', '', content, flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r'</div>\s*$', '', content.strip())

    # 2. Normalize groff h2 headings
    def fix_heading(match):
        title = match.group(1).strip()
        title_clean = re.sub(r'<[^>]+>', '', title).strip()
        return f'<h2>{title_clean}</h2>'

    content = re.sub(
        r'<h2>\s*([^\n<]+)\s*(?:<a\s+name="[^"]*">.*?</a>)?\s*</h2>',
        fix_heading,
        content,
        flags=re.IGNORECASE | re.DOTALL
    )
    content = re.sub(
        r'<h2>\s*([^\n<]+?)\s*\n\s*(?:<a\s+name="[^"]*"></a>\s*\n)?\s*</h2>',
        fix_heading,
        content,
        flags=re.IGNORECASE
    )
    content = re.sub(r'<a\s+name="[^"]*">\s*</a>', '', content, flags=re.IGNORECASE)

    # 3. Clean up internal groff Table of Contents (anchors, trailing <br>, and <hr>)
    content = re.sub(r'<a\s+href="#[^"]*">.*?</a>\s*(?:<br\s*/?>)?\s*', '', content, flags=re.IGNORECASE)
    content = re.sub(r'<hr\s*/?>', '', content, flags=re.IGNORECASE)

    # 4. Remove any stray <br> tags and excess blank lines between </h1> and <h2>
    content = re.sub(r'(</h1>)\s*(?:<br\s*/?>\s*)*\s*(<h2\b)', r'\1\n\n\2', content, flags=re.IGNORECASE)
    content = re.sub(r'(?:<br\s*/?>\s*){2,}', '<br>', content, flags=re.IGNORECASE)
    content = re.sub(r'<p\b[^>]*>\s*(?:<br\s*/?>)?\s*</p>', '', content, flags=re.IGNORECASE)

    # 5. Turn autolinks <http...> into proper <a> tags so Vue doesn't parse them as components
    def fix_autolink(match):
        url = match.group(1)
        clean_url = url.replace('/#47;', '/').replace('&#47;', '/')
        return f'<a href="{clean_url}" target="_blank" rel="noopener noreferrer">{clean_url}</a>'
    content = re.sub(r'<(https?://[^>]+)>', fix_autolink, content, flags=re.IGNORECASE)

    # 5. Tokenize HTML and balance tags
    pos = 0
    stack = []
    output = []

    for match in TAG_REGEX.finditer(content):
        # Text before tag
        text = content[pos:match.start()]
        output.append(text)
        pos = match.end()

        full_tag, is_close, tag_name, attrs = match.groups()
        tag_name = tag_name.lower()

        if tag_name in VOID_TAGS:
            output.append(f'<{tag_name}{attrs}>')
            continue

        if not is_close:
            # Opening tag
            # Implicit closing rules for standard HTML elements
            if tag_name == 'p' and stack and stack[-1] == 'p':
                output.append('</p>')
                stack.pop()
            elif tag_name == 'tr':
                while stack and stack[-1] in ('td', 'th', 'tr'):
                    output.append(f'</{stack.pop()}>')
            elif tag_name in ('td', 'th'):
                while stack and stack[-1] in ('td', 'th'):
                    output.append(f'</{stack.pop()}>')
            elif tag_name == 'table':
                if stack and stack[-1] == 'p':
                    output.append('</p>')
                    stack.pop()

            stack.append(tag_name)
            output.append(full_tag)
        else:
            # Closing tag
            if tag_name in stack:
                # Close any open tags nested inside tag_name
                while stack:
                    top = stack.pop()
                    output.append(f'</{top}>')
                    if top == tag_name:
                        break
            else:
                # Orphaned closing tag without a matching opening tag! Discard it.
                pass

    # Trailing text
    output.append(content[pos:])

    # Close any remaining unclosed tags
    while stack:
        output.append(f'</{stack.pop()}>')

    sanitized_body = ''.join(output).strip()

    # Wrap in VitePress-compatible container markdown
    return f"""<div v-pre class="man-page-content">

<div class="header-with-back">
  <div class="back-link">
    <a href="./zopen-reference">← Back</a>
  </div>
</div>

{sanitized_body}

</div>
"""

def main():
    parser = argparse.ArgumentParser(description="Sanitize groff man page HTML for VitePress.")
    parser.add_argument("input", nargs="?", help="Input HTML file (or stdin if omitted)")
    parser.add_argument("output", nargs="?", help="Output Markdown file (or stdout if omitted)")

    args = parser.parse_args()

    if args.input and args.input != "-":
        with open(args.input, "r", encoding="utf-8", errors="replace") as f:
            raw_content = f.read()
    else:
        raw_content = sys.stdin.read()

    sanitized = sanitize_man_html(raw_content)

    if args.output and args.output != "-":
        os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(sanitized)
    else:
        sys.stdout.write(sanitized)

if __name__ == "__main__":
    main()
